{% set name = "virocon" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/virocon-{{ version }}.tar.gz
  sha256: 2ae6838aa6f6d64388dcff066487882748c82d3ee6f6d33aa59d494c7c6f80ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=2.2.0
    - networkx
    - numpy
    - pandas
    - scikit-learn
    - scipy

test:
  imports:
    - virocon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/virocon-organization/virocon
  summary: ViroCon is a software to compute environmental contours
  license: MIT
  license_file: LICENSE
  doc_url: https://virocon.readthedocs.io
  dev_url: https://github.com/virocon-organization/virocon

extra:
  recipe-maintainers:
    - kawindme
