{% set name = "virocon" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/virocon-{{ version }}.tar.gz
  sha256: 117cb1213e3f31ebc01883e53de5f5198c4fa0090c5be1ecf4a19c5b1bc9f18f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base >=2.2.0
    - networkx
    - numpy
    - pandas
    - scikit-learn
    - scipy

test:
  imports:
    - virocon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/virocon-organization/virocon
  summary: ViroCon is a software to compute environmental contours
  license: MIT
  license_file: LICENSE
  doc_url: https://virocon.readthedocs.io
  dev_url: https://github.com/virocon-organization/virocon

extra:
  recipe-maintainers:
    - ahaselsteiner
    - kawindme
