{% set name = "virocon" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/virocon-{{ version }}.tar.gz
  sha256: 4ba34c32558a11ea73e46dd4ca1ccfdaeda9492a3f88b1f57a844d34b8449354

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base >=2.2.0
    - networkx
    - numpy
    - pandas
    - scikit-learn
    - scipy

test:
  imports:
    - virocon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/virocon-organization/virocon
  summary: ViroCon is a software to compute environmental contours
  license: MIT
  license_file: LICENSE
  doc_url: https://virocon.readthedocs.io
  dev_url: https://github.com/virocon-organization/virocon

extra:
  recipe-maintainers:
    - kawindme
